const rarityConfig = {
  "Common": { badge: "●", color: "#9ca3af" },
  "Rare": { badge: "★", color: "#ffffff" },
  "Double Rare": { badge: "★★", color: "#ffffff" },
  "Illustration Rare": { badge: "⭐", color: "#fbbf24" },
  "Special Illustration Rare": { badge: "⭐⭐", color: "#f59e0b" },
  "Pikachu Rare": { badge: "❤", color: "#facc15" },
  "Futuristic Rare": { badge: "✦", color: "#34d399" },
  "Classic Collection": { badge: "★C", color: "#e5e7eb" }
};

const cardData = {
  1: { cardNumber: "001", name: "Exeggcute", rarity: "Common" },
  2: { cardNumber: "002", name: "Alolan Exeggutor", rarity: "Common" },
  3: { cardNumber: "003", name: "Volbeat", rarity: "Common" },
  4: { cardNumber: "004", name: "Illumise", rarity: "Common" },
  5: { cardNumber: "005", name: "Tropius", rarity: "Common" },
  6: { cardNumber: "006", name: "Cherubi", rarity: "Common" },
  7: { cardNumber: "007", name: "Cherrim", rarity: "Common" },
  8: { cardNumber: "008", name: "Vivillon", rarity: "Common" },
  9: { cardNumber: "009", name: "Vulpix", rarity: "Common" },
  10: { cardNumber: "010", name: "Ninetales", rarity: "Common" },
  11: { cardNumber: "011", name: "Moltres", rarity: "Common" },
  12: { cardNumber: "012", name: "Ho-Oh", rarity: "Rare" },
  13: { cardNumber: "013", name: "Victini", rarity: "Common" },
  14: { cardNumber: "014", name: "Reshiram", rarity: "Rare" },
  15: { cardNumber: "015", name: "Fuecoco ex", rarity: "Double Rare" },
  16: { cardNumber: "016", name: "Slowpoke", rarity: "Common" },
  17: { cardNumber: "017", name: "Lapras", rarity: "Common" },
  18: { cardNumber: "018", name: "Articuno", rarity: "Common" },
  19: { cardNumber: "019", name: "Kyogre", rarity: "Rare" },
  20: { cardNumber: "020", name: "Palkia", rarity: "Rare" },
  21: { cardNumber: "021", name: "Greninja ex", rarity: "Double Rare" },
  22: { cardNumber: "022", name: "Wishiwashi", rarity: "Common" },
  23: { cardNumber: "023", name: "Pikachu", rarity: "Pikachu Rare" },
  24: { cardNumber: "024", name: "Pikachu", rarity: "Pikachu Rare" },
  25: { cardNumber: "025", name: "Pikachu", rarity: "Pikachu Rare" },
  26: { cardNumber: "026", name: "Pikachu", rarity: "Pikachu Rare" },
  27: { cardNumber: "027", name: "Pikachu", rarity: "Pikachu Rare" },
  28: { cardNumber: "028", name: "Pikachu", rarity: "Pikachu Rare" },
  29: { cardNumber: "029", name: "Pikachu", rarity: "Pikachu Rare" },
  30: { cardNumber: "030", name: "Pikachu", rarity: "Pikachu Rare" },
  31: { cardNumber: "031", name: "Pikachu", rarity: "Pikachu Rare" },
  32: { cardNumber: "032", name: "Pikachu", rarity: "Pikachu Rare" },
  33: { cardNumber: "033", name: "Pikachu", rarity: "Pikachu Rare" },
  34: { cardNumber: "034", name: "Pikachu", rarity: "Pikachu Rare" },
  35: { cardNumber: "035", name: "Pikachu", rarity: "Pikachu Rare" },
  36: { cardNumber: "036", name: "Pikachu", rarity: "Pikachu Rare" },
  37: { cardNumber: "037", name: "Pikachu", rarity: "Pikachu Rare" },
  38: { cardNumber: "038", name: "Pikachu", rarity: "Pikachu Rare" },
  39: { cardNumber: "039", name: "Pikachu", rarity: "Pikachu Rare" },
  40: { cardNumber: "040", name: "Pikachu", rarity: "Pikachu Rare" },
  41: { cardNumber: "041", name: "Pikachu", rarity: "Pikachu Rare" },
  42: { cardNumber: "042", name: "Pikachu", rarity: "Pikachu Rare" },
  43: { cardNumber: "043", name: "Pikachu", rarity: "Pikachu Rare" },
  44: { cardNumber: "044", name: "Pikachu", rarity: "Pikachu Rare" },
  45: { cardNumber: "045", name: "Pikachu", rarity: "Pikachu Rare" },
  46: { cardNumber: "046", name: "Pikachu", rarity: "Pikachu Rare" },
  47: { cardNumber: "047", name: "Pikachu", rarity: "Pikachu Rare" },
  48: { cardNumber: "048", name: "Pikachu", rarity: "Pikachu Rare" },
  49: { cardNumber: "049", name: "Pikachu", rarity: "Pikachu Rare" },
  50: { cardNumber: "050", name: "Pikachu", rarity: "Pikachu Rare" },
  51: { cardNumber: "051", name: "Pikachu", rarity: "Pikachu Rare" },
  52: { cardNumber: "052", name: "Pikachu", rarity: "Pikachu Rare" },
  53: { cardNumber: "053", name: "Pikachu ex", rarity: "Double Rare" },
  54: { cardNumber: "054", name: "Pikachu ex", rarity: "Double Rare" },
  55: { cardNumber: "055", name: "Zapdos", rarity: "Common" },
  56: { cardNumber: "056", name: "Zekrom", rarity: "Rare" },
  57: { cardNumber: "057", name: "Zeraora", rarity: "Common" },
  58: { cardNumber: "058", name: "Toxel", rarity: "Common" },
  59: { cardNumber: "059", name: "Toxtricity", rarity: "Common" },
  60: { cardNumber: "060", name: "Toxtricity", rarity: "Common" },
  61: { cardNumber: "061", name: "Morpeko", rarity: "Common" },
  62: { cardNumber: "062", name: "Miraidon", rarity: "Rare" },
  63: { cardNumber: "063", name: "Mewtwo", rarity: "Rare" },
  64: { cardNumber: "064", name: "Mewtwo ex", rarity: "Double Rare" },
  65: { cardNumber: "065", name: "Mew", rarity: "Rare" },
  66: { cardNumber: "066", name: "Mew ex", rarity: "Double Rare" },
  67: { cardNumber: "067", name: "Marill", rarity: "Common" },
  68: { cardNumber: "068", name: "Azumarill", rarity: "Common" },
  69: { cardNumber: "069", name: "Espeon", rarity: "Common" },
  70: { cardNumber: "070", name: "Espeon ex", rarity: "Double Rare" },
  71: { cardNumber: "071", name: "Sylveon ex", rarity: "Double Rare" },
  72: { cardNumber: "072", name: "Unown", rarity: "Common" },
  73: { cardNumber: "073", name: "Drifloon", rarity: "Common" },
  74: { cardNumber: "074", name: "Cresselia", rarity: "Common" },
  75: { cardNumber: "075", name: "Chandelure", rarity: "Common" },
  76: { cardNumber: "076", name: "Xerneas", rarity: "Rare" },
  77: { cardNumber: "077", name: "Comfey", rarity: "Common" },
  78: { cardNumber: "078", name: "Cosmog", rarity: "Common" },
  79: { cardNumber: "079", name: "Cosmoem", rarity: "Common" },
  80: { cardNumber: "080", name: "Lunala", rarity: "Rare" },
  81: { cardNumber: "081", name: "Gimmighoul", rarity: "Common" },
  82: { cardNumber: "082", name: "Groudon", rarity: "Rare" },
  83: { cardNumber: "083", name: "Lucario", rarity: "Common" },
  84: { cardNumber: "084", name: "Seismitoad", rarity: "Common" },
  85: { cardNumber: "085", name: "Lycanroc", rarity: "Common" },
  86: { cardNumber: "086", name: "Koraidon", rarity: "Rare" },
  87: { cardNumber: "087", name: "Nidoran♀", rarity: "Common" },
  88: { cardNumber: "088", name: "Nidorina", rarity: "Common" },
  89: { cardNumber: "089", name: "Alolan Meowth", rarity: "Common" },
  90: { cardNumber: "090", name: "Gengar ex", rarity: "Double Rare" },
  91: { cardNumber: "091", name: "Umbreon", rarity: "Common" },
  92: { cardNumber: "092", name: "Umbreon ex", rarity: "Double Rare" },
  93: { cardNumber: "093", name: "Murkrow", rarity: "Common" },
  94: { cardNumber: "094", name: "Scraggy", rarity: "Common" },
  95: { cardNumber: "095", name: "Zorua", rarity: "Common" },
  96: { cardNumber: "096", name: "Zoroark", rarity: "Common" },
  97: { cardNumber: "097", name: "Deino", rarity: "Common" },
  98: { cardNumber: "098", name: "Zweilous", rarity: "Common" },
  99: { cardNumber: "099", name: "Hydreigon", rarity: "Common" },
  100: { cardNumber: "100", name: "Yveltal", rarity: "Rare" },
  101: { cardNumber: "101", name: "Galarian Meowth", rarity: "Common" },
  102: { cardNumber: "102", name: "Jirachi ex", rarity: "Double Rare" },
  103: { cardNumber: "103", name: "Dialga", rarity: "Rare" },
  104: { cardNumber: "104", name: "Ferrothorn", rarity: "Common" },
  105: { cardNumber: "105", name: "Solgaleo", rarity: "Rare" },
  106: { cardNumber: "106", name: "Zacian", rarity: "Rare" },
  107: { cardNumber: "107", name: "Zamazenta", rarity: "Rare" },
  108: { cardNumber: "108", name: "Gholdengo", rarity: "Common" },
  109: { cardNumber: "109", name: "Salamence ex", rarity: "Double Rare" },
  110: { cardNumber: "110", name: "Jangmo-o", rarity: "Common" },
  111: { cardNumber: "111", name: "Hakamo-o", rarity: "Common" },
  112: { cardNumber: "112", name: "Kommo-o", rarity: "Common" },
  113: { cardNumber: "113", name: "Meowth", rarity: "Common" },
  114: { cardNumber: "114", name: "Kangaskhan", rarity: "Common" },
  115: { cardNumber: "115", name: "Ditto", rarity: "Common" },
  116: { cardNumber: "116", name: "Eevee", rarity: "Common" },
  117: { cardNumber: "117", name: "Eevee", rarity: "Common" },
  118: { cardNumber: "118", name: "Eevee", rarity: "Common" },
  119: { cardNumber: "119", name: "Snorlax", rarity: "Common" },
  120: { cardNumber: "120", name: "Igglybuff", rarity: "Common" },
  121: { cardNumber: "121", name: "Lugia", rarity: "Rare" },
  122: { cardNumber: "122", name: "Hisuian Zorua", rarity: "Common" },
  123: { cardNumber: "123", name: "Hisuian Zoroark", rarity: "Common" },
  124: { cardNumber: "124", name: "Minior", rarity: "Common" },
  125: { cardNumber: "125", name: "Maushold", rarity: "Common" },
  126: { cardNumber: "126", name: "Poké Pad", rarity: "Common" },
  127: { cardNumber: "127", name: "Switch", rarity: "Common" },
  128: { cardNumber: "128", name: "Ultra Ball", rarity: "Common" },
  129: { cardNumber: "129", name: "Alolan Exeggutor", rarity: "Illustration Rare" },
  130: { cardNumber: "130", name: "Moltres", rarity: "Illustration Rare" },
  131: { cardNumber: "131", name: "Lapras", rarity: "Illustration Rare" },
  132: { cardNumber: "132", name: "Articuno", rarity: "Illustration Rare" },
  133: { cardNumber: "133", name: "Zapdos", rarity: "Illustration Rare" },
  134: { cardNumber: "134", name: "Toxtricity", rarity: "Illustration Rare" },
  135: { cardNumber: "135", name: "Morpeko", rarity: "Illustration Rare" },
  136: { cardNumber: "136", name: "Drifloon", rarity: "Illustration Rare" },
  137: { cardNumber: "137", name: "Chandelure", rarity: "Illustration Rare" },
  138: { cardNumber: "138", name: "Lycanroc", rarity: "Illustration Rare" },
  139: { cardNumber: "139", name: "Alolan Meowth", rarity: "Illustration Rare" },
  140: { cardNumber: "140", name: "Scraggy", rarity: "Illustration Rare" },
  141: { cardNumber: "141", name: "Galarian Meowth", rarity: "Illustration Rare" },
  142: { cardNumber: "142", name: "Gholdengo", rarity: "Illustration Rare" },
  143: { cardNumber: "143", name: "Kommo-o", rarity: "Illustration Rare" },
  144: { cardNumber: "144", name: "Meowth", rarity: "Illustration Rare" },
  145: { cardNumber: "145", name: "Hisuian Zorua", rarity: "Illustration Rare" },
  146: { cardNumber: "146", name: "Maushold", rarity: "Illustration Rare" },
  147: { cardNumber: "147", name: "Fuecoco ex", rarity: "Special Illustration Rare" },
  148: { cardNumber: "148", name: "Greninja ex", rarity: "Special Illustration Rare" },
  149: { cardNumber: "149", name: "Pikachu ex", rarity: "Special Illustration Rare" },
  150: { cardNumber: "150", name: "Pikachu ex", rarity: "Special Illustration Rare" },
  151: { cardNumber: "151", name: "Mewtwo ex", rarity: "Special Illustration Rare" },
  152: { cardNumber: "152", name: "Mew ex", rarity: "Special Illustration Rare" },
  153: { cardNumber: "153", name: "Sylveon ex", rarity: "Special Illustration Rare" },
  154: { cardNumber: "154", name: "Gengar ex", rarity: "Special Illustration Rare" },
  155: { cardNumber: "155", name: "Jirachi ex", rarity: "Special Illustration Rare" },
  156: { cardNumber: "156", name: "Salamence ex", rarity: "Special Illustration Rare" },
  157: { cardNumber: "157", name: "Mewtwo ex", rarity: "Futuristic Rare" },
  158: { cardNumber: "158", name: "Mew ex", rarity: "Futuristic Rare" },
  159: { cardNumber: "58", name: "Pikachu", rarity: "Classic Collection" },
  160: { cardNumber: "4", name: "Charizard", rarity: "Classic Collection" },
  161: { cardNumber: "5", name: "Delcatty", rarity: "Classic Collection" },
  162: { cardNumber: "11", name: "Metagross δ", rarity: "Classic Collection" },
  163: { cardNumber: "11", name: "Genesect-EX", rarity: "Classic Collection" },
  164: { cardNumber: "18", name: "Misty", rarity: "Classic Collection" },
  165: { cardNumber: "19", name: "Dark Tyranitar", rarity: "Classic Collection" },
  166: { cardNumber: "25", name: "Sneasel", rarity: "Classic Collection" },
  167: { cardNumber: "33", name: "Pikachu & Zekrom-GX", rarity: "Classic Collection" },
  168: { cardNumber: "41", name: "Greninja BREAK", rarity: "Classic Collection" },
  169: { cardNumber: "43", name: "Uxie", rarity: "Classic Collection" },
  170: { cardNumber: "47", name: "Crobat", rarity: "Classic Collection" },
  171: { cardNumber: "50", name: "Raikou", rarity: "Classic Collection" },
  172: { cardNumber: "57", name: "Buzzwole-GX", rarity: "Classic Collection" },
  173: { cardNumber: "69", name: "Erika’s Jigglypuff", rarity: "Classic Collection" },
  174: { cardNumber: "85", name: "Rayquaza-EX", rarity: "Classic Collection" },
  175: { cardNumber: "89", name: "Solgaleo-GX", rarity: "Classic Collection" },
  176: { cardNumber: "94", name: "Gengar", rarity: "Classic Collection" },
  177: { cardNumber: "99", name: "Darkrai & Cresselia LEGEND", rarity: "Classic Collection" },
  178: { cardNumber: "100", name: "Darkrai & Cresselia LEGEND", rarity: "Classic Collection" },
  179: { cardNumber: "101", name: "N", rarity: "Classic Collection" },
  180: { cardNumber: "106", name: "Palkia LV.X", rarity: "Classic Collection" },
  181: { cardNumber: "106", name: "Shining Celebi", rarity: "Classic Collection" },
  182: { cardNumber: "106", name: "M Gardevoir-EX", rarity: "Classic Collection" },
  183: { cardNumber: "108", name: "Scizor ex", rarity: "Classic Collection" },
  184: { cardNumber: "114", name: "Mew VMAX", rarity: "Classic Collection" },
  185: { cardNumber: "123", name: "Arceus VSTAR", rarity: "Classic Collection" },
  186: { cardNumber: "138", name: "Zacian V", rarity: "Classic Collection" },
  187: { cardNumber: "149", name: "Lugia", rarity: "Classic Collection" },
  188: { cardNumber: "203", name: "Magikarp", rarity: "Classic Collection" },
  189: { cardNumber: "009", name: "Basic Energy (Grass)", rarity: "Common" },
  190: { cardNumber: "010", name: "Basic Energy (Fire)", rarity: "Common" },
  191: { cardNumber: "011", name: "Basic Energy (Water)", rarity: "Common" },
  192: { cardNumber: "012", name: "Basic Energy (Lightning)", rarity: "Common" },
  193: { cardNumber: "013", name: "Basic Energy (Psychic)", rarity: "Common" },
  194: { cardNumber: "014", name: "Basic Energy (Fighting)", rarity: "Common" },
  195: { cardNumber: "015", name: "Basic Energy (Darkness)", rarity: "Common" },
  196: { cardNumber: "016", name: "Basic Energy (Metal)", rarity: "Common" }
};

